# Site wide configuration

title: The Forest of Music
locale: en_US

#description: 
logo: site-logo.png
search: true
url: http://jamiemori.github.io/
#url: http://localhost:4000

# Jekyll configuration
permalink: /:categories/:title/
markdown: kramdown
highlighter: rogue
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-sitemap

kramdown:
  input: GFM
  #mathjax: true
  ##auto_ids: true
  #kentity_output: as_char
  #toc_levels: 1..2
  #enable_coderay: false

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]


# Site owner
owner:
  name: Jamie Mori
  avatar: bio-photo.jpg
  email: taronaoi@gmail.com
  disqus-shortname: theforestofmusic
  twitter: #username
  facebook: #username
  github: #username
  stackexchange: #http://stackoverflow.com/users/123456/username
  linkedin: https://www.linkedin.com/pub/taro-naoi/20/30/933
  instagram: #username
  flickr: #username
  tumblr: #username
  pinterest: #username
  weibo: #userid
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
